<?php
/**
 * Created by PhpStorm.
 * User: finley
 * Date: 2018/6/3
 * Time: 11:34
 */

namespace app\admin\controller;
use app\api\service\Token;
use think\Auth;
use think\Controller;
use think\Request;
use think\session;
use \app\common\model\Curd as CurdModel;
use app\common\Model\Common;
class Base extends Controller
{
   /* public function __construct(Request $request = null)
{
    parent::__construct($request);
//        $res = session('adminUser');
    if(empty($res)){
        $this->redirect('Login/index');
    }

      $auth = new Auth();
      $request = Request::instance();
      if (!$auth->check($request->module() . '-' . $request->controller() . '-' . $request->action(), $res['uid'])) {// 第一个参数是规则名称,第二个参数是用户UID
//             return array('status'=>'error','msg'=>'有权限！');
          $this->error('你没有权限','login/index');
          if(empty($res)){
              $this->redirect('Login/index');
          }
      }
}*/

    public function _initialize()
    {

        parent::_initialize(); // TODO: Change the autogenerated stub
        $res = session('adminUser');
        $uid = $res['id'];
        if(!$uid){
            $this->error("请先登录!",'Login/index');
        }elseif ($uid==1){
            return true;
        }
        $request = Request::instance();
        $name = $request->module() . '/' . $request->controller() . '/' . $request->action();
        $nocheck = ['admin/Index/index','admin/Index/welcome','admin/Login/index'];
        if(in_array($name,$nocheck)){
            return true;
        }
        $auth = new Auth();
        if ($auth->check($name, $res['id'])===false) {// 第一个参数是规则名称,第二个参数是用户UID
            $this->error('你没有权限访问');
            if(empty($res)){
                $this->error("您还没有登录！",'Login/index');
            }
        }

    }

    /**
     * 一般表的CURD操作
     * @throws \Exception
     */
    public function curd(){
        if($_POST) {
            $data = $this->request->post();
            $table = $this->request->post('table');
            try{
                $CommonModel = new CurdModel($table);
                $CommonModel->TableCRUD($data);
            }catch(\Exception $e){
                throw $e;
            }
            return show(1, '操作成功');
        }
        return show(0,'操作异常');
    }

    /**
     * 排序功能
     */
    function listorder()
    {
        $listorder = $_POST['listorder'];
        $table = $this->request->post('table');
        if ($listorder) {
            foreach ($listorder as $menuId => $v) {
                // 执行更新
                $Curd = new CurdModel($table);
                $result = $Curd->listUpdate($menuId, $v);
            }
            return show(1, '排序成功');
        }
        return show(0, '排序数据失败');
    }

}